import Head from "next/head";
import Image from "next/image";

import { FaGlobe, FaGithub, FaYoutube, FaRegEnvelope } from "react-icons/fa";
import {
  DiCss3,
  DiReact,
  DiNodejsSmall,
  DiAws,
  DiNpm,
  DiGit,
  DiHtml5,
  DiSass,
  DiPostgresql,
  DiMongodb,
  DiDocker,
  DiWordpress,
} from "react-icons/di";
import { SiJest, SiTypescript } from "react-icons/si";

import styles from "../sass/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.image_wrapper}>
        <Image
          src={"/images/breakingWave.jpg"}
          layout="fill"
          objectFit="cover"
        />
      </div>
      <section className={styles.projectHero}>
        <h1>Projects</h1>
      </section>
      <section className={styles.projects}>
        <div className={styles.project}>
          <div className={styles.projectInfoBox}>
            <div className={styles.infoBox}>
              <h1>Title</h1>
              <p>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                Doloribus iusto expedita molestias nam, ipsa incidunt minima,
                asperiores culpa nesciunt voluptas distinctio, quidem dolore
                dolores. Odio animi harum enim, facere aliquam dignissimos
                vitae!
              </p>
              <ul>
                <li>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto
                  earum sit minima numquam dicta consequuntur quasi?
                </li>
                <li>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto
                  earum sit minima numquam dicta consequuntur quasi?
                </li>
                <li>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto
                  earum sit minima numquam dicta consequuntur quasi?
                </li>
                <li>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto
                  earum sit minima numquam dicta consequuntur quasi?
                </li>
                <li>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto
                  earum sit minima numquam dicta consequuntur quasi?
                </li>
              </ul>
              <div className={styles.project_btns}>
                <div className={styles.linkBtn}>
                  <FaGithub /> <a href="#">Github</a>
                </div>
                <div className={styles.linkBtn}>
                  <FaGlobe />
                  <a href="#">Live Link</a>
                </div>
                <div className={styles.linkBtn}>
                  <FaYoutube />
                  <a href="#">Walkthrough</a>
                </div>
              </div>
            </div>
          </div>
          <div className={styles.projectImageBox}></div>
        </div>
        <div className={styles.project}>
          <div className={styles.projectInfoBox}>
            <div className={styles.infoBox}>
              <h1>Title</h1>
              <p>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                Doloribus iusto expedita molestias nam, ipsa incidunt minima,
                asperiores culpa nesciunt voluptas distinctio, quidem dolore
                dolores. Odio animi harum enim, facere aliquam dignissimos
                vitae!
              </p>
              <ul className={styles.list}>
                <li>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto
                  earum sit minima numquam dicta consequuntur quasi?
                </li>
                <li>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto
                  earum sit minima numquam dicta consequuntur quasi?
                </li>
                <li>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto
                  earum sit minima numquam dicta consequuntur quasi?
                </li>
                <li>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto
                  earum sit minima numquam dicta consequuntur quasi?
                </li>
                <li>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto
                  earum sit minima numquam dicta consequuntur quasi?
                </li>
              </ul>
              <div className={styles.project_btns}>
                <div className={styles.linkBtn}>
                  <FaGithub /> <a href="#">Github</a>
                </div>
                <div className={styles.linkBtn}>
                  <FaGlobe />
                  <a href="#">Live Link</a>
                </div>
                <div className={styles.linkBtn}>
                  <FaYoutube />
                  <a href="#">Walkthrough</a>
                </div>
              </div>
            </div>
          </div>
          <div className={styles.projectImageBox}>
            <div className={styles.image_1}>
              <Image
                src={"/images/beach1.jpg"}
                layout="fill"
                objectFit="cover"
              />
            </div>
            <div className={styles.image_2}>
              <Image
                src={"/images/beach2.jpg"}
                layout="fill"
                objectFit="cover"
              />
            </div>
            <div className={styles.image_3}>
              <Image
                src={"/images/beach3.jpg"}
                layout="fill"
                objectFit="cover"
              />
            </div>
          </div>
        </div>
      </section>
      <section className={styles.skills}>
        <h1>Skills &amp; Tools</h1>
        <div className={styles.skillsBox}>
          <DiCss3 size={80} className={styles.margin} />
          <DiReact size={80} className={styles.margin} />
          <DiNodejsSmall size={80} className={styles.margin} />
          <DiAws size={80} className={styles.margin} />
          <DiHtml5 size={80} className={styles.margin} />
          <DiNpm size={80} className={styles.margin} />
          <DiGit size={80} className={styles.margin} />
          <DiSass size={80} className={styles.margin} />
          <DiPostgresql size={80} className={styles.margin} />
          <DiMongodb size={80} className={styles.margin} />
          <DiWordpress size={80} className={styles.margin} />
          <DiDocker size={80} className={styles.margin} />
          <SiJest size={80} className={styles.margin} />
          <SiTypescript size={80} />
        </div>
      </section>
      <section className={styles.contact}>
        <div className={styles.contactBox}>
          <div className={styles.contact_leftbox}>
            <h1>Get In Touch</h1>
            <form action="" className={styles.form}>
              <label htmlFor="name" className={styles.label}>Name</label>
              <input type="text" className={styles.input}/>
              <label htmlFor="email" className={styles.label}>Email</label>
              <input type="text" className={styles.input}/>
              <label htmlFor="Message" className={styles.label}>Message</label>
              <textarea name="message" cols="30" rows="10" className={styles.message}></textarea>
              <button>Send Email <FaRegEnvelope/></button>
            </form>
          </div>
          <div className={styles.contact_social}>
              <a href="http://" target="_blank" rel="noopener noreferrer"><FaGithub/></a>
              <a href=""></a>
          </div>
        </div>
      </section>
    </div>
  );
}
